[package]
name = "ai_assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite = "0.36.1"
dotenvy = "0.15.7"
reqwest = { version = "0.12.9", features = ["json", "blocking"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
httparse = "1.9.5"
